"""Coverage reporting.

This is the project's most useful artefact long before any packaging happens.
"We cover 63% of BlackArch and 91% of Kali" is a recruiting tool, a roadmap and
an honest answer to "can this replace my distro?" all at once. Publish it.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict

from .catalog import DISTROS, Catalog
from .taxonomy import Taxonomy

TIER_LABEL = {
    1: "in nixpkgs",
    2: "mechanically packageable",
    3: "manual work",
    4: "will not package",
}


def compute(catalog: Catalog, taxonomy: Taxonomy) -> dict:
    total = len(catalog)
    packaged = sum(1 for t in catalog if t.packaged)

    per_distro = {}
    for distro in DISTROS:
        members = [t for t in catalog if distro in t.provenance]
        covered = [t for t in members if t.packaged]
        per_distro[distro] = {
            "tools": len(members),
            "packaged": len(covered),
            "percent": round(100 * len(covered) / len(members), 1) if members else 0.0,
        }

    tiers = Counter(t.tier for t in catalog)
    per_category: dict[str, dict] = {}
    for cat in taxonomy.keys:
        members = catalog.in_category(cat)
        covered = [t for t in members if t.packaged]
        per_category[cat] = {
            "tools": len(members),
            "packaged": len(covered),
            "percent": round(100 * len(covered) / len(members), 1) if members else 0.0,
        }

    # How much of each distro is unique to it -- tells you what you lose by
    # dropping a source from scope.
    exclusivity = {}
    for distro in DISTROS:
        members = [t for t in catalog if distro in t.provenance]
        only = [t for t in members if len(t.provenance) == 1]
        exclusivity[distro] = {
            "unique": len(only),
            "percent": round(100 * len(only) / len(members), 1) if members else 0.0,
        }

    return {
        "total": total,
        "packaged": packaged,
        "percent": round(100 * packaged / total, 1) if total else 0.0,
        "tiers": {str(k): tiers.get(k, 0) for k in sorted(TIER_LABEL)},
        "distros": per_distro,
        "exclusivity": exclusivity,
        "categories": per_category,
        "capabilities": dict(
            Counter(c for t in catalog for c in t.capabilities)
        ),
    }


def to_markdown(report: dict, taxonomy: Taxonomy) -> str:
    lines = [
        "# Coverage",
        "",
        "<!-- generated by `arsenal coverage`; do not edit -->",
        "",
        f"**{report['packaged']} of {report['total']} catalogued tools "
        f"({report['percent']}%) resolve to a Nix package.**",
        "",
        "## By source distribution",
        "",
        "| Distro | Tools | Packaged | Coverage | Unique to it |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for distro, row in report["distros"].items():
        uniq = report["exclusivity"][distro]
        lines.append(
            f"| {distro} | {row['tools']} | {row['packaged']} | "
            f"{row['percent']}% | {uniq['unique']} ({uniq['percent']}%) |"
        )

    if all(row["tools"] == 0 for row in report["distros"].values()):
        lines += [
            "",
            "> All zero because no importer has run yet -- provenance is populated by",
            "> `arsenal import <distro>`, not by hand. Until then the catalog is just",
            "> the hand-curated seed set and these numbers mean nothing.",
        ]

    lines += ["", "## By tier", "", "| Tier | Meaning | Tools |", "| --- | --- | ---: |"]
    for tier, label in TIER_LABEL.items():
        lines.append(f"| {tier} | {label} | {report['tiers'].get(str(tier), 0)} |")

    lines += ["", "## By category", "", "| Category | Tools | Packaged | Coverage |",
              "| --- | ---: | ---: | ---: |"]
    for key, row in sorted(
        report["categories"].items(), key=lambda kv: -kv[1]["tools"]
    ):
        label = taxonomy.categories[key].label if key in taxonomy.categories else key
        lines.append(
            f"| {label} (`{key}`) | {row['tools']} | {row['packaged']} | {row['percent']}% |"
        )

    if report["capabilities"]:
        lines += [
            "", "## Tools requiring elevated capabilities", "",
            "These need the NixOS module (or manual `setcap`/`sudo`). "
            "A devShell alone cannot grant them.", "",
            "| Capability | Tools |", "| --- | ---: |",
        ]
        for cap, count in sorted(report["capabilities"].items(), key=lambda kv: -kv[1]):
            lines.append(f"| `{cap}` | {count} |")

    return "\n".join(lines) + "\n"


def to_json(report: dict) -> str:
    return json.dumps(report, indent=2, sort_keys=True) + "\n"
